### ISSUE TITLE
John Merideth & John Reese speaker pages 404

### ISSUE THREAD

**Issue by jamesmosier** [stirtrek/stirtrek.github.io#13]
Hi! I know it is a bit late, but I noticed John Merideth & John Reese's speaker pages are missing. 

https://stirtrek.com/Speakers/2019/John-Merideth.html

https://stirtrek.com/Speakers/2019/John-Reese.html

Looking forward to tomorrow! :tada:

**Comment by jaredfaris** [comment]
John Merideth asked us to rename his page to Jack Merideth - https://stirtrek.com/Speakers/2019/Jack-Merideth.html. In the future I'll try to setup a redirect... sorry about that.

John Reese is no longer speaking so was removed from the site.

Please make sure to clear your cache if you're seeing old results. I appreciate you following up on both of these!
